pub mod auth_service;
pub mod color_service;
pub mod emotion_service;
pub mod place_service;
pub mod statistics_service;
pub mod think_emotion_service;
pub mod think_service;
pub mod trash_service;
pub mod users_service;
